apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
  namespace: test-namespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: reg.qiniu.com/hao/http-test:latest
        imagePullPolicy: IfNotPresent
        name: http-test
        env:
        - name: ERR_RATE
          value: "10"
        - name: GIN_MODE
          value: "release"
        - name: VERSION
          value: "v1"
        ports:
        - containerPort: 3000
