apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-deploy-test
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio-deploy-test-role-binding
  labels:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-deploy-test-role
subjects:
  - kind: ServiceAccount
    name: istio-deploy-test
    namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: istio-deploy-test-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-test
  namespace: istio-system
spec:
  template:
    spec:
      serviceAccountName: istio-deploy-test
      containers:
        - name: deploy-test
          image: "reg.qiniu.com/hao/deploy-test:latest"
      restartPolicy: Never